<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\CategoryTree;
use App\Models\Product;
use App\Models\PurchaseDetail;
use App\Models\Shop;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        Category::query()->insert([
            ['name' => '食料品'],
            ['name' => '日用品'],
            ['name' => '野菜'],
            ['name' => '果物'],
            ['name' => '魚'],
            ['name' => '肉'],
            ['name' => '肉加工品'],
            ['name' => '惣菜'],
            ['name' => 'パン・シリアル'],
            ['name' => '乳製品'],
            ['name' => '冷凍食品'],
            ['name' => '卵'],
            ['name' => '調味料'],
            ['name' => '乾物'],
            ['name' => '粉類'],
            ['name' => '缶詰'],
            ['name' => '麺類'],
            ['name' => 'インスタント麺'],
            ['name' => 'お菓子・スイーツ'],
            ['name' => 'レトルト'],
            ['name' => '米'],
            ['name' => '汁物'],
            ['name' => '漬物'],
            ['name' => '製菓材料'],
            ['name' => 'アイスクリーム'],
            ['name' => '瓶詰'],
            ['name' => '弁当'],
            ['name' => '大豆製品'],
            ['name' => 'おつまみ'],
            ['name' => 'ソフトドリンク'],
            ['name' => 'コーヒー'],
            ['name' => '紅茶'],
            ['name' => 'お茶'],
            ['name' => '水'],
            ['name' => '穀類(パン・米・麺以外)'],
            ['name' => '紙製品'],
            ['name' => '医療品'],
            ['name' => '洗濯用洗剤'],
            ['name' => '住宅用洗剤'],
            ['name' => '台所用洗剤'],
            ['name' => '風呂用洗剤'],
            ['name' => 'トイレ用洗剤'],
            ['name' => '台所用品'],
            ['name' => '風呂用品'],
            ['name' => 'トイレ用品'],
            ['name' => '洗濯用品'],
            ['name' => '掃除用品'],
            ['name' => 'オーラルケア用品'],
            ['name' => 'ボディケア用品'],
            ['name' => 'スキンケア用品'],
            ['name' => 'ヘアケア用品'],
            ['name' => 'フェイスケア商品'],
            ['name' => '入浴剤'],
            ['name' => 'トラベル用品'],
            ['name' => '化粧品'],
            ['name' => '化粧小物'],
            ['name' => '生理用品'],
            ['name' => '乾電池'],
            ['name' => '医薬品'],
            ['name' => 'ベビー用品'],
            ['name' => 'ペット用品'],
            ['name' => '文房具'],
            ['name' => '家庭用品'],
            ['name' => '衣類'],
            ['name' => '工具'],
            ['name' => 'ケア用品'],
            ['name' => '健康食品'],
            ['name' => '家庭用化学製品'],
            ['name' => 'たまねぎ'],
            ['name' => '大根'],
            ['name' => 'きゅうり'],
            ['name' => 'にんじん'],
            ['name' => 'トマト'],
            ['name' => 'キャベツ'],
            ['name' => 'ピーマン'],
            ['name' => 'アスパラガス'],
            ['name' => 'ブロッコリー'],
            ['name' => 'もやし'],
            ['name' => 'ねぎ'],
            ['name' => 'なす'],
            ['name' => 'いも類'],
            ['name' => '根菜'],
            ['name' => 'きのこ'],
            ['name' => 'かぼちゃ'],
            ['name' => 'とうもろこし'],
            ['name' => '葉もの野菜'],
            ['name' => '豆類（野菜）'],
            ['name' => 'パプリカ'],
            ['name' => 'カットサラダ'],
            ['name' => 'カット野菜'],
            ['name' => 'その他（野菜）'],
            ['name' => 'いちご'],
            ['name' => 'りんご'],
            ['name' => 'オレンジ'],
            ['name' => 'グレープフルーツ'],
            ['name' => 'みかん・柑橘類'],
            ['name' => 'バナナ'],
            ['name' => 'キウイフルーツ'],
            ['name' => 'ぶどう'],
            ['name' => 'メロン'],
            ['name' => 'パイナップル'],
            ['name' => 'もも'],
            ['name' => 'さくらんぼ'],
            ['name' => 'すいか'],
            ['name' => 'なし'],
            ['name' => 'ベリー類'],
            ['name' => 'レモン'],
            ['name' => 'カットフルーツ'],
            ['name' => 'その他（果物）'],
            ['name' => '鮮魚'],
            ['name' => 'その他（魚）'],
            ['name' => '鶏肉'],
            ['name' => '牛肉'],
            ['name' => '豚肉'],
            ['name' => '合いびき肉'],
            ['name' => 'その他（肉）'],
            ['name' => 'ハム・ベーコン'],
            ['name' => 'ソーセージ'],
            ['name' => 'ローストビーフ'],
            ['name' => '生ハム'],
            ['name' => 'お弁当'],
            ['name' => '焼き鳥'],
            ['name' => '揚げ物'],
            ['name' => 'サラダ等'],
            ['name' => '寿司'],
            ['name' => 'その他（惣菜）'],
            ['name' => '菓子パン'],
            ['name' => '食パン'],
            ['name' => 'シリアル'],
            ['name' => '牛乳'],
            ['name' => '豆乳'],
            ['name' => 'ヨーグルト'],
            ['name' => '生クリーム'],
            ['name' => 'バター・マーガリン'],
            ['name' => 'チーズ'],
            ['name' => 'ホイップクリーム'],
            ['name' => '冷凍麺・パスタ'],
            ['name' => '冷凍弁当おかず'],
            ['name' => '冷凍惣菜'],
            ['name' => 'その他（冷凍食品）'],
            ['name' => ''],
            ['name' => '甘味料・砂糖'],
            ['name' => '味噌'],
            ['name' => 'ソース'],
            ['name' => '醤油'],
            ['name' => 'お酢'],
            ['name' => 'みりん'],
            ['name' => 'たれ・つゆ'],
            ['name' => 'ケチャップ・マヨネーズ'],
            ['name' => '塩'],
            ['name' => 'ポン酢'],
            ['name' => '薬味'],
            ['name' => 'ハーブ'],
            ['name' => 'スパイス'],
            ['name' => 'オイル'],
            ['name' => '料理酒'],
            ['name' => 'ドレッシング'],
            ['name' => 'その他（調味料）'],
            ['name' => 'ごま'],
            ['name' => '昆布'],
            ['name' => 'のり'],
            ['name' => 'ふりかけ'],
            ['name' => '乾燥わかめ・ひじき'],
            ['name' => '干しもの'],
            ['name' => 'お茶漬け'],
            ['name' => '乾燥野菜'],
            ['name' => 'その他（乾物）'],
            ['name' => '小麦粉'],
            ['name' => 'パン粉'],
            ['name' => '片栗粉'],
            ['name' => 'てんぷら粉'],
            ['name' => '唐揚げ粉'],
            ['name' => 'お好み・たこ焼き粉'],
            ['name' => 'その他（コーンスターチ等）'],
            ['name' => '魚類'],
            ['name' => '肉類'],
            ['name' => '野菜類'],
            ['name' => '豆類'],
            ['name' => 'キノコ類'],
            ['name' => 'フルーツ'],
            ['name' => 'スープ'],
            ['name' => 'うどん'],
            ['name' => 'そうめん'],
            ['name' => 'そば'],
            ['name' => 'パスタ'],
            ['name' => 'ラーメン'],
            ['name' => 'やきそば'],
            ['name' => 'その他（冷麺等）'],
            ['name' => 'カップラーメン'],
            ['name' => 'カップ麺（その他）'],
            ['name' => 'スープパスタ'],
            ['name' => 'その他インスタント麺'],
            ['name' => '洋菓子'],
            ['name' => '和菓子'],
            ['name' => 'スナック'],
            ['name' => '駄菓子'],
            ['name' => 'チョコレート'],
            ['name' => 'ビスケット・クッキー・クラッカー'],
            ['name' => 'おつまみ'],
            ['name' => 'せんべい'],
            ['name' => 'ガム・アメ・ミント'],
            ['name' => 'マシュマロ'],
            ['name' => 'プリン'],
            ['name' => 'ゼリー'],
            ['name' => 'ナッツ'],
            ['name' => 'その他（お菓子）'],
            ['name' => 'カレー'],
            ['name' => 'ハヤシ'],
            ['name' => 'シチュー'],
            ['name' => 'イタリアン'],
            ['name' => '中華'],
            ['name' => 'スープ・味噌汁'],
            ['name' => '米'],
            ['name' => 'その他（レトルト）'],
            ['name' => '味噌汁'],
            ['name' => '凝固剤・添加物'],
            ['name' => '製菓用ナッツ'],
            ['name' => '製菓用フルーツ'],
            ['name' => '粉類'],
            ['name' => '製菓用チョコ'],
            ['name' => 'トッピング'],
            ['name' => 'ジャム'],
            ['name' => 'コンポート'],
            ['name' => '魚介類'],
            ['name' => '調味料'],
            ['name' => 'その他（瓶詰）'],
            ['name' => '厚揚げ'],
            ['name' => '豆腐'],
            ['name' => '納豆'],
            ['name' => 'その他（大豆製品）'],
            ['name' => 'するめ・いか'],
            ['name' => 'その他魚介類'],
            ['name' => 'サラミ'],
            ['name' => 'その他（おつまみ）'],
            ['name' => '果実飲料'],
            ['name' => '乳酸飲料'],
            ['name' => '炭酸飲料'],
            ['name' => 'スポーツドリンク'],
            ['name' => '健康飲料'],
            ['name' => '豆乳類'],
            ['name' => '野菜ジュース'],
            ['name' => 'その他（ソフトドリンク）'],
            ['name' => '無糖'],
            ['name' => '微糖'],
            ['name' => '低糖'],
            ['name' => 'カフェラテ等'],
            ['name' => 'レギュラー'],
            ['name' => 'インスタント（コーヒー）'],
            ['name' => 'インスタント（紅茶）'],
            ['name' => 'ティーバック'],
            ['name' => 'ハーブティー'],
            ['name' => 'ペットボトル（紅茶）'],
            ['name' => '日本茶'],
            ['name' => '中国茶'],
            ['name' => 'ペットボトル（お茶）'],
            ['name' => 'トイレットペーパー'],
            ['name' => 'ティシュ'],
            ['name' => 'ウェットティッシュ'],
            ['name' => '絆創膏'],
            ['name' => 'マスク'],
            ['name' => 'その他（医療品）'],
            ['name' => '衣類用漂白剤'],
            ['name' => 'ホームクリーニング剤'],
            ['name' => '柔軟剤'],
            ['name' => 'タイル用'],
            ['name' => 'ガラス用'],
            ['name' => '床用'],
            ['name' => 'クレンザー'],
            ['name' => '食器用漂白剤'],
            ['name' => '食器用'],
            ['name' => 'たわし'],
            ['name' => 'スポンジ'],
            ['name' => 'キッチンペーパー'],
            ['name' => 'ラップ・アルミホイル'],
            ['name' => '食器'],
            ['name' => '調理器具'],
            ['name' => 'その他（台所用品）'],
            ['name' => 'ボディタオル'],
            ['name' => '風呂マット'],
            ['name' => 'その他（風呂用品）'],
            ['name' => '歯ブラシ'],
            ['name' => '歯磨き粉'],
            ['name' => '洗口剤'],
            ['name' => '歯間ブラシ'],
            ['name' => '石鹸'],
            ['name' => 'ハンドソープ'],
            ['name' => 'ボディソープ'],
            ['name' => 'ハンドクリーム'],
            ['name' => 'リップクリーム'],
            ['name' => '日焼け止め'],
            ['name' => 'シャンプー'],
            ['name' => 'コンディショナー'],
            ['name' => 'トリートメント'],
            ['name' => 'ヘアカラー'],
            ['name' => 'ヘアワックス'],
            ['name' => 'ヘアスプレー'],
            ['name' => '洗顔フォーム'],
            ['name' => 'クレンジング'],
            ['name' => 'メイク落とし'],
            ['name' => 'フェイスメイク'],
            ['name' => 'アイメイク'],
            ['name' => '口紅'],
            ['name' => '化粧水'],
            ['name' => '乳液'],
            ['name' => '美容液'],
            ['name' => 'パック'],
            ['name' => 'ネイル'],
            ['name' => '殺虫剤'],
            ['name' => '防虫剤'],
            ['name' => '消臭剤'],
        ]);

        CategoryTree::query()->insert([
            ['parent_id' => 1, 'child_id' => 1, 'depth' => 0],
            ['parent_id' => 2, 'child_id' => 2, 'depth' => 0],
            ['parent_id' => 3, 'child_id' => 3, 'depth' => 0],
            ['parent_id' => 4, 'child_id' => 4, 'depth' => 0],
            ['parent_id' => 5, 'child_id' => 5, 'depth' => 0],
            ['parent_id' => 6, 'child_id' => 6, 'depth' => 0],
            ['parent_id' => 7, 'child_id' => 7, 'depth' => 0],
            ['parent_id' => 8, 'child_id' => 8, 'depth' => 0],
            ['parent_id' => 9, 'child_id' => 9, 'depth' => 0],
            ['parent_id' => 10, 'child_id' => 10, 'depth' => 0],
            ['parent_id' => 11, 'child_id' => 11, 'depth' => 0],
            ['parent_id' => 12, 'child_id' => 12, 'depth' => 0],
            ['parent_id' => 13, 'child_id' => 13, 'depth' => 0],
            ['parent_id' => 14, 'child_id' => 14, 'depth' => 0],
            ['parent_id' => 15, 'child_id' => 15, 'depth' => 0],
            ['parent_id' => 16, 'child_id' => 16, 'depth' => 0],
            ['parent_id' => 17, 'child_id' => 17, 'depth' => 0],
            ['parent_id' => 18, 'child_id' => 18, 'depth' => 0],
            ['parent_id' => 19, 'child_id' => 19, 'depth' => 0],
            ['parent_id' => 20, 'child_id' => 20, 'depth' => 0],
            ['parent_id' => 21, 'child_id' => 21, 'depth' => 0],
            ['parent_id' => 22, 'child_id' => 22, 'depth' => 0],
            ['parent_id' => 23, 'child_id' => 23, 'depth' => 0],
            ['parent_id' => 24, 'child_id' => 24, 'depth' => 0],
            ['parent_id' => 25, 'child_id' => 25, 'depth' => 0],
            ['parent_id' => 26, 'child_id' => 26, 'depth' => 0],
            ['parent_id' => 27, 'child_id' => 27, 'depth' => 0],
            ['parent_id' => 28, 'child_id' => 28, 'depth' => 0],
            ['parent_id' => 29, 'child_id' => 29, 'depth' => 0],
            ['parent_id' => 30, 'child_id' => 30, 'depth' => 0],
            ['parent_id' => 31, 'child_id' => 31, 'depth' => 0],
            ['parent_id' => 32, 'child_id' => 32, 'depth' => 0],
            ['parent_id' => 33, 'child_id' => 33, 'depth' => 0],
            ['parent_id' => 34, 'child_id' => 34, 'depth' => 0],
            ['parent_id' => 35, 'child_id' => 35, 'depth' => 0],
            ['parent_id' => 36, 'child_id' => 36, 'depth' => 0],
            ['parent_id' => 37, 'child_id' => 37, 'depth' => 0],
            ['parent_id' => 38, 'child_id' => 38, 'depth' => 0],
            ['parent_id' => 39, 'child_id' => 39, 'depth' => 0],
            ['parent_id' => 40, 'child_id' => 40, 'depth' => 0],
            ['parent_id' => 41, 'child_id' => 41, 'depth' => 0],
            ['parent_id' => 42, 'child_id' => 42, 'depth' => 0],
            ['parent_id' => 43, 'child_id' => 43, 'depth' => 0],
            ['parent_id' => 44, 'child_id' => 44, 'depth' => 0],
            ['parent_id' => 45, 'child_id' => 45, 'depth' => 0],
            ['parent_id' => 46, 'child_id' => 46, 'depth' => 0],
            ['parent_id' => 47, 'child_id' => 47, 'depth' => 0],
            ['parent_id' => 48, 'child_id' => 48, 'depth' => 0],
            ['parent_id' => 49, 'child_id' => 49, 'depth' => 0],
            ['parent_id' => 50, 'child_id' => 50, 'depth' => 0],
            ['parent_id' => 51, 'child_id' => 51, 'depth' => 0],
            ['parent_id' => 52, 'child_id' => 52, 'depth' => 0],
            ['parent_id' => 53, 'child_id' => 53, 'depth' => 0],
            ['parent_id' => 54, 'child_id' => 54, 'depth' => 0],
            ['parent_id' => 55, 'child_id' => 55, 'depth' => 0],
            ['parent_id' => 56, 'child_id' => 56, 'depth' => 0],
            ['parent_id' => 57, 'child_id' => 57, 'depth' => 0],
            ['parent_id' => 58, 'child_id' => 58, 'depth' => 0],
            ['parent_id' => 59, 'child_id' => 59, 'depth' => 0],
            ['parent_id' => 60, 'child_id' => 60, 'depth' => 0],
            ['parent_id' => 61, 'child_id' => 61, 'depth' => 0],
            ['parent_id' => 62, 'child_id' => 62, 'depth' => 0],
            ['parent_id' => 63, 'child_id' => 63, 'depth' => 0],
            ['parent_id' => 64, 'child_id' => 64, 'depth' => 0],
            ['parent_id' => 65, 'child_id' => 65, 'depth' => 0],
            ['parent_id' => 66, 'child_id' => 66, 'depth' => 0],
            ['parent_id' => 67, 'child_id' => 67, 'depth' => 0],
            ['parent_id' => 68, 'child_id' => 68, 'depth' => 0],
            ['parent_id' => 69, 'child_id' => 69, 'depth' => 0],
            ['parent_id' => 70, 'child_id' => 70, 'depth' => 0],
            ['parent_id' => 71, 'child_id' => 71, 'depth' => 0],
            ['parent_id' => 72, 'child_id' => 72, 'depth' => 0],
            ['parent_id' => 73, 'child_id' => 73, 'depth' => 0],
            ['parent_id' => 74, 'child_id' => 74, 'depth' => 0],
            ['parent_id' => 75, 'child_id' => 75, 'depth' => 0],
            ['parent_id' => 76, 'child_id' => 76, 'depth' => 0],
            ['parent_id' => 77, 'child_id' => 77, 'depth' => 0],
            ['parent_id' => 78, 'child_id' => 78, 'depth' => 0],
            ['parent_id' => 79, 'child_id' => 79, 'depth' => 0],
            ['parent_id' => 80, 'child_id' => 80, 'depth' => 0],
            ['parent_id' => 81, 'child_id' => 81, 'depth' => 0],
            ['parent_id' => 82, 'child_id' => 82, 'depth' => 0],
            ['parent_id' => 83, 'child_id' => 83, 'depth' => 0],
            ['parent_id' => 84, 'child_id' => 84, 'depth' => 0],
            ['parent_id' => 85, 'child_id' => 85, 'depth' => 0],
            ['parent_id' => 86, 'child_id' => 86, 'depth' => 0],
            ['parent_id' => 87, 'child_id' => 87, 'depth' => 0],
            ['parent_id' => 88, 'child_id' => 88, 'depth' => 0],
            ['parent_id' => 89, 'child_id' => 89, 'depth' => 0],
            ['parent_id' => 90, 'child_id' => 90, 'depth' => 0],
            ['parent_id' => 91, 'child_id' => 91, 'depth' => 0],
            ['parent_id' => 92, 'child_id' => 92, 'depth' => 0],
            ['parent_id' => 93, 'child_id' => 93, 'depth' => 0],
            ['parent_id' => 94, 'child_id' => 94, 'depth' => 0],
            ['parent_id' => 95, 'child_id' => 95, 'depth' => 0],
            ['parent_id' => 96, 'child_id' => 96, 'depth' => 0],
            ['parent_id' => 97, 'child_id' => 97, 'depth' => 0],
            ['parent_id' => 98, 'child_id' => 98, 'depth' => 0],
            ['parent_id' => 99, 'child_id' => 99, 'depth' => 0],
            ['parent_id' => 100, 'child_id' => 100, 'depth' => 0],
            ['parent_id' => 101, 'child_id' => 101, 'depth' => 0],
            ['parent_id' => 102, 'child_id' => 102, 'depth' => 0],
            ['parent_id' => 103, 'child_id' => 103, 'depth' => 0],
            ['parent_id' => 104, 'child_id' => 104, 'depth' => 0],
            ['parent_id' => 105, 'child_id' => 105, 'depth' => 0],
            ['parent_id' => 106, 'child_id' => 106, 'depth' => 0],
            ['parent_id' => 107, 'child_id' => 107, 'depth' => 0],
            ['parent_id' => 108, 'child_id' => 108, 'depth' => 0],
            ['parent_id' => 109, 'child_id' => 109, 'depth' => 0],
            ['parent_id' => 110, 'child_id' => 110, 'depth' => 0],
            ['parent_id' => 111, 'child_id' => 111, 'depth' => 0],
            ['parent_id' => 112, 'child_id' => 112, 'depth' => 0],
            ['parent_id' => 113, 'child_id' => 113, 'depth' => 0],
            ['parent_id' => 114, 'child_id' => 114, 'depth' => 0],
            ['parent_id' => 115, 'child_id' => 115, 'depth' => 0],
            ['parent_id' => 116, 'child_id' => 116, 'depth' => 0],
            ['parent_id' => 117, 'child_id' => 117, 'depth' => 0],
            ['parent_id' => 118, 'child_id' => 118, 'depth' => 0],
            ['parent_id' => 119, 'child_id' => 119, 'depth' => 0],
            ['parent_id' => 120, 'child_id' => 120, 'depth' => 0],
            ['parent_id' => 121, 'child_id' => 121, 'depth' => 0],
            ['parent_id' => 122, 'child_id' => 122, 'depth' => 0],
            ['parent_id' => 123, 'child_id' => 123, 'depth' => 0],
            ['parent_id' => 124, 'child_id' => 124, 'depth' => 0],
            ['parent_id' => 125, 'child_id' => 125, 'depth' => 0],
            ['parent_id' => 126, 'child_id' => 126, 'depth' => 0],
            ['parent_id' => 127, 'child_id' => 127, 'depth' => 0],
            ['parent_id' => 128, 'child_id' => 128, 'depth' => 0],
            ['parent_id' => 129, 'child_id' => 129, 'depth' => 0],
            ['parent_id' => 130, 'child_id' => 130, 'depth' => 0],
            ['parent_id' => 131, 'child_id' => 131, 'depth' => 0],
            ['parent_id' => 132, 'child_id' => 132, 'depth' => 0],
            ['parent_id' => 133, 'child_id' => 133, 'depth' => 0],
            ['parent_id' => 134, 'child_id' => 134, 'depth' => 0],
            ['parent_id' => 135, 'child_id' => 135, 'depth' => 0],
            ['parent_id' => 136, 'child_id' => 136, 'depth' => 0],
            ['parent_id' => 137, 'child_id' => 137, 'depth' => 0],
            ['parent_id' => 138, 'child_id' => 138, 'depth' => 0],
            ['parent_id' => 139, 'child_id' => 139, 'depth' => 0],
            ['parent_id' => 140, 'child_id' => 140, 'depth' => 0],
            ['parent_id' => 141, 'child_id' => 141, 'depth' => 0],
            ['parent_id' => 142, 'child_id' => 142, 'depth' => 0],
            ['parent_id' => 143, 'child_id' => 143, 'depth' => 0],
            ['parent_id' => 144, 'child_id' => 144, 'depth' => 0],
            ['parent_id' => 145, 'child_id' => 145, 'depth' => 0],
            ['parent_id' => 146, 'child_id' => 146, 'depth' => 0],
            ['parent_id' => 147, 'child_id' => 147, 'depth' => 0],
            ['parent_id' => 148, 'child_id' => 148, 'depth' => 0],
            ['parent_id' => 149, 'child_id' => 149, 'depth' => 0],
            ['parent_id' => 150, 'child_id' => 150, 'depth' => 0],
            ['parent_id' => 151, 'child_id' => 151, 'depth' => 0],
            ['parent_id' => 152, 'child_id' => 152, 'depth' => 0],
            ['parent_id' => 153, 'child_id' => 153, 'depth' => 0],
            ['parent_id' => 154, 'child_id' => 154, 'depth' => 0],
            ['parent_id' => 155, 'child_id' => 155, 'depth' => 0],
            ['parent_id' => 156, 'child_id' => 156, 'depth' => 0],
            ['parent_id' => 157, 'child_id' => 157, 'depth' => 0],
            ['parent_id' => 158, 'child_id' => 158, 'depth' => 0],
            ['parent_id' => 159, 'child_id' => 159, 'depth' => 0],
            ['parent_id' => 160, 'child_id' => 160, 'depth' => 0],
            ['parent_id' => 161, 'child_id' => 161, 'depth' => 0],
            ['parent_id' => 162, 'child_id' => 162, 'depth' => 0],
            ['parent_id' => 163, 'child_id' => 163, 'depth' => 0],
            ['parent_id' => 164, 'child_id' => 164, 'depth' => 0],
            ['parent_id' => 165, 'child_id' => 165, 'depth' => 0],
            ['parent_id' => 166, 'child_id' => 166, 'depth' => 0],
            ['parent_id' => 167, 'child_id' => 167, 'depth' => 0],
            ['parent_id' => 168, 'child_id' => 168, 'depth' => 0],
            ['parent_id' => 169, 'child_id' => 169, 'depth' => 0],
            ['parent_id' => 170, 'child_id' => 170, 'depth' => 0],
            ['parent_id' => 171, 'child_id' => 171, 'depth' => 0],
            ['parent_id' => 172, 'child_id' => 172, 'depth' => 0],
            ['parent_id' => 173, 'child_id' => 173, 'depth' => 0],
            ['parent_id' => 174, 'child_id' => 174, 'depth' => 0],
            ['parent_id' => 175, 'child_id' => 175, 'depth' => 0],
            ['parent_id' => 176, 'child_id' => 176, 'depth' => 0],
            ['parent_id' => 177, 'child_id' => 177, 'depth' => 0],
            ['parent_id' => 178, 'child_id' => 178, 'depth' => 0],
            ['parent_id' => 179, 'child_id' => 179, 'depth' => 0],
            ['parent_id' => 180, 'child_id' => 180, 'depth' => 0],
            ['parent_id' => 181, 'child_id' => 181, 'depth' => 0],
            ['parent_id' => 182, 'child_id' => 182, 'depth' => 0],
            ['parent_id' => 183, 'child_id' => 183, 'depth' => 0],
            ['parent_id' => 184, 'child_id' => 184, 'depth' => 0],
            ['parent_id' => 185, 'child_id' => 185, 'depth' => 0],
            ['parent_id' => 186, 'child_id' => 186, 'depth' => 0],
            ['parent_id' => 187, 'child_id' => 187, 'depth' => 0],
            ['parent_id' => 188, 'child_id' => 188, 'depth' => 0],
            ['parent_id' => 189, 'child_id' => 189, 'depth' => 0],
            ['parent_id' => 190, 'child_id' => 190, 'depth' => 0],
            ['parent_id' => 191, 'child_id' => 191, 'depth' => 0],
            ['parent_id' => 192, 'child_id' => 192, 'depth' => 0],
            ['parent_id' => 193, 'child_id' => 193, 'depth' => 0],
            ['parent_id' => 194, 'child_id' => 194, 'depth' => 0],
            ['parent_id' => 195, 'child_id' => 195, 'depth' => 0],
            ['parent_id' => 196, 'child_id' => 196, 'depth' => 0],
            ['parent_id' => 197, 'child_id' => 197, 'depth' => 0],
            ['parent_id' => 198, 'child_id' => 198, 'depth' => 0],
            ['parent_id' => 199, 'child_id' => 199, 'depth' => 0],
            ['parent_id' => 200, 'child_id' => 200, 'depth' => 0],
            ['parent_id' => 201, 'child_id' => 201, 'depth' => 0],
            ['parent_id' => 202, 'child_id' => 202, 'depth' => 0],
            ['parent_id' => 203, 'child_id' => 203, 'depth' => 0],
            ['parent_id' => 204, 'child_id' => 204, 'depth' => 0],
            ['parent_id' => 205, 'child_id' => 205, 'depth' => 0],
            ['parent_id' => 206, 'child_id' => 206, 'depth' => 0],
            ['parent_id' => 207, 'child_id' => 207, 'depth' => 0],
            ['parent_id' => 208, 'child_id' => 208, 'depth' => 0],
            ['parent_id' => 209, 'child_id' => 209, 'depth' => 0],
            ['parent_id' => 210, 'child_id' => 210, 'depth' => 0],
            ['parent_id' => 211, 'child_id' => 211, 'depth' => 0],
            ['parent_id' => 212, 'child_id' => 212, 'depth' => 0],
            ['parent_id' => 213, 'child_id' => 213, 'depth' => 0],
            ['parent_id' => 214, 'child_id' => 214, 'depth' => 0],
            ['parent_id' => 215, 'child_id' => 215, 'depth' => 0],
            ['parent_id' => 216, 'child_id' => 216, 'depth' => 0],
            ['parent_id' => 217, 'child_id' => 217, 'depth' => 0],
            ['parent_id' => 218, 'child_id' => 218, 'depth' => 0],
            ['parent_id' => 219, 'child_id' => 219, 'depth' => 0],
            ['parent_id' => 220, 'child_id' => 220, 'depth' => 0],
            ['parent_id' => 221, 'child_id' => 221, 'depth' => 0],
            ['parent_id' => 222, 'child_id' => 222, 'depth' => 0],
            ['parent_id' => 223, 'child_id' => 223, 'depth' => 0],
            ['parent_id' => 224, 'child_id' => 224, 'depth' => 0],
            ['parent_id' => 225, 'child_id' => 225, 'depth' => 0],
            ['parent_id' => 226, 'child_id' => 226, 'depth' => 0],
            ['parent_id' => 227, 'child_id' => 227, 'depth' => 0],
            ['parent_id' => 228, 'child_id' => 228, 'depth' => 0],
            ['parent_id' => 229, 'child_id' => 229, 'depth' => 0],
            ['parent_id' => 230, 'child_id' => 230, 'depth' => 0],
            ['parent_id' => 231, 'child_id' => 231, 'depth' => 0],
            ['parent_id' => 232, 'child_id' => 232, 'depth' => 0],
            ['parent_id' => 233, 'child_id' => 233, 'depth' => 0],
            ['parent_id' => 234, 'child_id' => 234, 'depth' => 0],
            ['parent_id' => 235, 'child_id' => 235, 'depth' => 0],
            ['parent_id' => 236, 'child_id' => 236, 'depth' => 0],
            ['parent_id' => 237, 'child_id' => 237, 'depth' => 0],
            ['parent_id' => 238, 'child_id' => 238, 'depth' => 0],
            ['parent_id' => 239, 'child_id' => 239, 'depth' => 0],
            ['parent_id' => 240, 'child_id' => 240, 'depth' => 0],
            ['parent_id' => 241, 'child_id' => 241, 'depth' => 0],
            ['parent_id' => 242, 'child_id' => 242, 'depth' => 0],
            ['parent_id' => 243, 'child_id' => 243, 'depth' => 0],
            ['parent_id' => 244, 'child_id' => 244, 'depth' => 0],
            ['parent_id' => 245, 'child_id' => 245, 'depth' => 0],
            ['parent_id' => 246, 'child_id' => 246, 'depth' => 0],
            ['parent_id' => 247, 'child_id' => 247, 'depth' => 0],
            ['parent_id' => 248, 'child_id' => 248, 'depth' => 0],
            ['parent_id' => 249, 'child_id' => 249, 'depth' => 0],
            ['parent_id' => 250, 'child_id' => 250, 'depth' => 0],
            ['parent_id' => 251, 'child_id' => 251, 'depth' => 0],
            ['parent_id' => 252, 'child_id' => 252, 'depth' => 0],
            ['parent_id' => 253, 'child_id' => 253, 'depth' => 0],
            ['parent_id' => 254, 'child_id' => 254, 'depth' => 0],
            ['parent_id' => 255, 'child_id' => 255, 'depth' => 0],
            ['parent_id' => 256, 'child_id' => 256, 'depth' => 0],
            ['parent_id' => 257, 'child_id' => 257, 'depth' => 0],
            ['parent_id' => 258, 'child_id' => 258, 'depth' => 0],
            ['parent_id' => 259, 'child_id' => 259, 'depth' => 0],
            ['parent_id' => 260, 'child_id' => 260, 'depth' => 0],
            ['parent_id' => 261, 'child_id' => 261, 'depth' => 0],
            ['parent_id' => 262, 'child_id' => 262, 'depth' => 0],
            ['parent_id' => 263, 'child_id' => 263, 'depth' => 0],
            ['parent_id' => 264, 'child_id' => 264, 'depth' => 0],
            ['parent_id' => 265, 'child_id' => 265, 'depth' => 0],
            ['parent_id' => 266, 'child_id' => 266, 'depth' => 0],
            ['parent_id' => 267, 'child_id' => 267, 'depth' => 0],
            ['parent_id' => 268, 'child_id' => 268, 'depth' => 0],
            ['parent_id' => 269, 'child_id' => 269, 'depth' => 0],
            ['parent_id' => 270, 'child_id' => 270, 'depth' => 0],
            ['parent_id' => 271, 'child_id' => 271, 'depth' => 0],
            ['parent_id' => 272, 'child_id' => 272, 'depth' => 0],
            ['parent_id' => 273, 'child_id' => 273, 'depth' => 0],
            ['parent_id' => 274, 'child_id' => 274, 'depth' => 0],
            ['parent_id' => 275, 'child_id' => 275, 'depth' => 0],
            ['parent_id' => 276, 'child_id' => 276, 'depth' => 0],
            ['parent_id' => 277, 'child_id' => 277, 'depth' => 0],
            ['parent_id' => 278, 'child_id' => 278, 'depth' => 0],
            ['parent_id' => 279, 'child_id' => 279, 'depth' => 0],
            ['parent_id' => 280, 'child_id' => 280, 'depth' => 0],
            ['parent_id' => 281, 'child_id' => 281, 'depth' => 0],
            ['parent_id' => 282, 'child_id' => 282, 'depth' => 0],
            ['parent_id' => 283, 'child_id' => 283, 'depth' => 0],
            ['parent_id' => 284, 'child_id' => 284, 'depth' => 0],
            ['parent_id' => 285, 'child_id' => 285, 'depth' => 0],
            ['parent_id' => 286, 'child_id' => 286, 'depth' => 0],
            ['parent_id' => 287, 'child_id' => 287, 'depth' => 0],
            ['parent_id' => 288, 'child_id' => 288, 'depth' => 0],
            ['parent_id' => 289, 'child_id' => 289, 'depth' => 0],
            ['parent_id' => 290, 'child_id' => 290, 'depth' => 0],
            ['parent_id' => 291, 'child_id' => 291, 'depth' => 0],
            ['parent_id' => 292, 'child_id' => 292, 'depth' => 0],
            ['parent_id' => 293, 'child_id' => 293, 'depth' => 0],
            ['parent_id' => 294, 'child_id' => 294, 'depth' => 0],
            ['parent_id' => 295, 'child_id' => 295, 'depth' => 0],
            ['parent_id' => 296, 'child_id' => 296, 'depth' => 0],
            ['parent_id' => 297, 'child_id' => 297, 'depth' => 0],
            ['parent_id' => 298, 'child_id' => 298, 'depth' => 0],
            ['parent_id' => 299, 'child_id' => 299, 'depth' => 0],
            ['parent_id' => 300, 'child_id' => 300, 'depth' => 0],
            ['parent_id' => 301, 'child_id' => 301, 'depth' => 0],
            ['parent_id' => 302, 'child_id' => 302, 'depth' => 0],
            ['parent_id' => 303, 'child_id' => 303, 'depth' => 0],
            ['parent_id' => 304, 'child_id' => 304, 'depth' => 0],
            ['parent_id' => 305, 'child_id' => 305, 'depth' => 0],
            ['parent_id' => 306, 'child_id' => 306, 'depth' => 0],
            ['parent_id' => 307, 'child_id' => 307, 'depth' => 0],
            ['parent_id' => 308, 'child_id' => 308, 'depth' => 0],
            ['parent_id' => 309, 'child_id' => 309, 'depth' => 0],
            ['parent_id' => 310, 'child_id' => 310, 'depth' => 0],
            ['parent_id' => 1, 'child_id' => 3, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 4, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 5, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 6, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 7, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 8, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 9, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 10, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 11, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 12, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 13, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 14, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 15, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 16, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 17, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 18, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 19, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 20, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 21, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 22, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 23, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 24, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 25, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 26, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 27, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 28, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 29, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 30, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 31, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 32, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 33, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 34, 'depth' => 1],
            ['parent_id' => 1, 'child_id' => 35, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 36, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 37, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 38, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 39, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 40, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 41, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 42, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 43, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 44, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 45, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 46, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 47, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 48, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 49, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 50, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 51, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 52, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 53, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 54, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 55, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 56, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 57, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 58, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 59, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 60, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 61, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 62, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 63, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 64, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 65, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 66, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 67, 'depth' => 1],
            ['parent_id' => 2, 'child_id' => 68, 'depth' => 1],
            ['parent_id' => 3, 'child_id' => 69, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 70, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 71, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 72, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 73, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 74, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 75, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 76, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 77, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 78, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 79, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 80, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 81, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 82, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 83, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 84, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 85, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 86, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 87, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 88, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 89, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 90, 'depth' => 2],
            ['parent_id' => 3, 'child_id' => 91, 'depth' => 2],
            ['parent_id' => 4, 'child_id' => 92, 'depth' => 2],
            ['parent_id' => 4, 'child_id' => 93, 'depth' => 2],
            ['parent_id' => 4, 'child_id' => 94, 'depth' => 2],
            ['parent_id' => 4, 'child_id' => 95, 'depth' => 2],
            ['parent_id' => 4, 'child_id' => 96, 'depth' => 2],
            ['parent_id' => 4, 'child_id' => 97, 'depth' => 2],
            ['parent_id' => 4, 'child_id' => 98, 'depth' => 2],
            ['parent_id' => 4, 'child_id' => 99, 'depth' => 2],
            ['parent_id' => 4, 'child_id' => 100, 'depth' => 2],
            ['parent_id' => 4, 'child_id' => 101, 'depth' => 2],
            ['parent_id' => 4, 'child_id' => 102, 'depth' => 2],
            ['parent_id' => 4, 'child_id' => 103, 'depth' => 2],
            ['parent_id' => 4, 'child_id' => 104, 'depth' => 2],
            ['parent_id' => 4, 'child_id' => 105, 'depth' => 2],
            ['parent_id' => 4, 'child_id' => 106, 'depth' => 2],
            ['parent_id' => 4, 'child_id' => 107, 'depth' => 2],
            ['parent_id' => 4, 'child_id' => 108, 'depth' => 2],
            ['parent_id' => 4, 'child_id' => 109, 'depth' => 2],
            ['parent_id' => 5, 'child_id' => 110, 'depth' => 2],
            ['parent_id' => 5, 'child_id' => 111, 'depth' => 2],
            ['parent_id' => 6, 'child_id' => 112, 'depth' => 2],
            ['parent_id' => 6, 'child_id' => 113, 'depth' => 2],
            ['parent_id' => 6, 'child_id' => 114, 'depth' => 2],
            ['parent_id' => 6, 'child_id' => 115, 'depth' => 2],
            ['parent_id' => 6, 'child_id' => 116, 'depth' => 2],
            ['parent_id' => 7, 'child_id' => 117, 'depth' => 2],
            ['parent_id' => 7, 'child_id' => 118, 'depth' => 2],
            ['parent_id' => 7, 'child_id' => 119, 'depth' => 2],
            ['parent_id' => 7, 'child_id' => 120, 'depth' => 2],
            ['parent_id' => 8, 'child_id' => 121, 'depth' => 2],
            ['parent_id' => 8, 'child_id' => 122, 'depth' => 2],
            ['parent_id' => 8, 'child_id' => 123, 'depth' => 2],
            ['parent_id' => 8, 'child_id' => 124, 'depth' => 2],
            ['parent_id' => 8, 'child_id' => 125, 'depth' => 2],
            ['parent_id' => 8, 'child_id' => 126, 'depth' => 2],
            ['parent_id' => 9, 'child_id' => 127, 'depth' => 2],
            ['parent_id' => 9, 'child_id' => 128, 'depth' => 2],
            ['parent_id' => 9, 'child_id' => 129, 'depth' => 2],
            ['parent_id' => 10, 'child_id' => 130, 'depth' => 2],
            ['parent_id' => 10, 'child_id' => 131, 'depth' => 2],
            ['parent_id' => 10, 'child_id' => 132, 'depth' => 2],
            ['parent_id' => 10, 'child_id' => 133, 'depth' => 2],
            ['parent_id' => 10, 'child_id' => 134, 'depth' => 2],
            ['parent_id' => 10, 'child_id' => 135, 'depth' => 2],
            ['parent_id' => 10, 'child_id' => 136, 'depth' => 2],
            ['parent_id' => 11, 'child_id' => 137, 'depth' => 2],
            ['parent_id' => 11, 'child_id' => 138, 'depth' => 2],
            ['parent_id' => 11, 'child_id' => 139, 'depth' => 2],
            ['parent_id' => 11, 'child_id' => 140, 'depth' => 2],
            ['parent_id' => 12, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 13, 'child_id' => 142, 'depth' => 2],
            ['parent_id' => 13, 'child_id' => 143, 'depth' => 2],
            ['parent_id' => 13, 'child_id' => 144, 'depth' => 2],
            ['parent_id' => 13, 'child_id' => 145, 'depth' => 2],
            ['parent_id' => 13, 'child_id' => 146, 'depth' => 2],
            ['parent_id' => 13, 'child_id' => 147, 'depth' => 2],
            ['parent_id' => 13, 'child_id' => 148, 'depth' => 2],
            ['parent_id' => 13, 'child_id' => 149, 'depth' => 2],
            ['parent_id' => 13, 'child_id' => 150, 'depth' => 2],
            ['parent_id' => 13, 'child_id' => 151, 'depth' => 2],
            ['parent_id' => 13, 'child_id' => 152, 'depth' => 2],
            ['parent_id' => 13, 'child_id' => 153, 'depth' => 2],
            ['parent_id' => 13, 'child_id' => 154, 'depth' => 2],
            ['parent_id' => 13, 'child_id' => 155, 'depth' => 2],
            ['parent_id' => 13, 'child_id' => 156, 'depth' => 2],
            ['parent_id' => 13, 'child_id' => 157, 'depth' => 2],
            ['parent_id' => 13, 'child_id' => 158, 'depth' => 2],
            ['parent_id' => 14, 'child_id' => 159, 'depth' => 2],
            ['parent_id' => 14, 'child_id' => 160, 'depth' => 2],
            ['parent_id' => 14, 'child_id' => 161, 'depth' => 2],
            ['parent_id' => 14, 'child_id' => 162, 'depth' => 2],
            ['parent_id' => 14, 'child_id' => 163, 'depth' => 2],
            ['parent_id' => 14, 'child_id' => 164, 'depth' => 2],
            ['parent_id' => 14, 'child_id' => 165, 'depth' => 2],
            ['parent_id' => 14, 'child_id' => 166, 'depth' => 2],
            ['parent_id' => 14, 'child_id' => 167, 'depth' => 2],
            ['parent_id' => 15, 'child_id' => 168, 'depth' => 2],
            ['parent_id' => 15, 'child_id' => 169, 'depth' => 2],
            ['parent_id' => 15, 'child_id' => 170, 'depth' => 2],
            ['parent_id' => 15, 'child_id' => 171, 'depth' => 2],
            ['parent_id' => 15, 'child_id' => 172, 'depth' => 2],
            ['parent_id' => 15, 'child_id' => 173, 'depth' => 2],
            ['parent_id' => 15, 'child_id' => 174, 'depth' => 2],
            ['parent_id' => 16, 'child_id' => 175, 'depth' => 2],
            ['parent_id' => 16, 'child_id' => 176, 'depth' => 2],
            ['parent_id' => 16, 'child_id' => 177, 'depth' => 2],
            ['parent_id' => 16, 'child_id' => 178, 'depth' => 2],
            ['parent_id' => 16, 'child_id' => 179, 'depth' => 2],
            ['parent_id' => 16, 'child_id' => 180, 'depth' => 2],
            ['parent_id' => 16, 'child_id' => 144, 'depth' => 2],
            ['parent_id' => 16, 'child_id' => 181, 'depth' => 2],
            ['parent_id' => 17, 'child_id' => 182, 'depth' => 2],
            ['parent_id' => 17, 'child_id' => 183, 'depth' => 2],
            ['parent_id' => 17, 'child_id' => 184, 'depth' => 2],
            ['parent_id' => 17, 'child_id' => 185, 'depth' => 2],
            ['parent_id' => 17, 'child_id' => 186, 'depth' => 2],
            ['parent_id' => 17, 'child_id' => 187, 'depth' => 2],
            ['parent_id' => 17, 'child_id' => 188, 'depth' => 2],
            ['parent_id' => 18, 'child_id' => 189, 'depth' => 2],
            ['parent_id' => 18, 'child_id' => 190, 'depth' => 2],
            ['parent_id' => 18, 'child_id' => 191, 'depth' => 2],
            ['parent_id' => 18, 'child_id' => 192, 'depth' => 2],
            ['parent_id' => 19, 'child_id' => 193, 'depth' => 2],
            ['parent_id' => 19, 'child_id' => 194, 'depth' => 2],
            ['parent_id' => 19, 'child_id' => 195, 'depth' => 2],
            ['parent_id' => 19, 'child_id' => 196, 'depth' => 2],
            ['parent_id' => 19, 'child_id' => 197, 'depth' => 2],
            ['parent_id' => 19, 'child_id' => 198, 'depth' => 2],
            ['parent_id' => 19, 'child_id' => 29, 'depth' => 2],
            ['parent_id' => 19, 'child_id' => 200, 'depth' => 2],
            ['parent_id' => 19, 'child_id' => 201, 'depth' => 2],
            ['parent_id' => 19, 'child_id' => 202, 'depth' => 2],
            ['parent_id' => 19, 'child_id' => 203, 'depth' => 2],
            ['parent_id' => 19, 'child_id' => 204, 'depth' => 2],
            ['parent_id' => 19, 'child_id' => 205, 'depth' => 2],
            ['parent_id' => 19, 'child_id' => 206, 'depth' => 2],
            ['parent_id' => 20, 'child_id' => 207, 'depth' => 2],
            ['parent_id' => 20, 'child_id' => 208, 'depth' => 2],
            ['parent_id' => 20, 'child_id' => 209, 'depth' => 2],
            ['parent_id' => 20, 'child_id' => 210, 'depth' => 2],
            ['parent_id' => 20, 'child_id' => 211, 'depth' => 2],
            ['parent_id' => 20, 'child_id' => 212, 'depth' => 2],
            ['parent_id' => 20, 'child_id' => 21, 'depth' => 2],
            ['parent_id' => 20, 'child_id' => 214, 'depth' => 2],
            ['parent_id' => 21, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 22, 'child_id' => 215, 'depth' => 2],
            ['parent_id' => 22, 'child_id' => 181, 'depth' => 2],
            ['parent_id' => 23, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 24, 'child_id' => 216, 'depth' => 2],
            ['parent_id' => 24, 'child_id' => 217, 'depth' => 2],
            ['parent_id' => 24, 'child_id' => 218, 'depth' => 2],
            ['parent_id' => 24, 'child_id' => 15, 'depth' => 2],
            ['parent_id' => 24, 'child_id' => 220, 'depth' => 2],
            ['parent_id' => 24, 'child_id' => 221, 'depth' => 2],
            ['parent_id' => 25, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 26, 'child_id' => 222, 'depth' => 2],
            ['parent_id' => 26, 'child_id' => 223, 'depth' => 2],
            ['parent_id' => 26, 'child_id' => 197, 'depth' => 2],
            ['parent_id' => 26, 'child_id' => 224, 'depth' => 2],
            ['parent_id' => 26, 'child_id' => 176, 'depth' => 2],
            ['parent_id' => 26, 'child_id' => 177, 'depth' => 2],
            ['parent_id' => 26, 'child_id' => 179, 'depth' => 2],
            ['parent_id' => 26, 'child_id' => 178, 'depth' => 2],
            ['parent_id' => 26, 'child_id' => 13, 'depth' => 2],
            ['parent_id' => 26, 'child_id' => 226, 'depth' => 2],
            ['parent_id' => 27, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 28, 'child_id' => 227, 'depth' => 2],
            ['parent_id' => 28, 'child_id' => 228, 'depth' => 2],
            ['parent_id' => 28, 'child_id' => 229, 'depth' => 2],
            ['parent_id' => 28, 'child_id' => 230, 'depth' => 2],
            ['parent_id' => 29, 'child_id' => 231, 'depth' => 2],
            ['parent_id' => 29, 'child_id' => 232, 'depth' => 2],
            ['parent_id' => 29, 'child_id' => 233, 'depth' => 2],
            ['parent_id' => 29, 'child_id' => 135, 'depth' => 2],
            ['parent_id' => 29, 'child_id' => 234, 'depth' => 2],
            ['parent_id' => 30, 'child_id' => 235, 'depth' => 2],
            ['parent_id' => 30, 'child_id' => 236, 'depth' => 2],
            ['parent_id' => 30, 'child_id' => 237, 'depth' => 2],
            ['parent_id' => 30, 'child_id' => 238, 'depth' => 2],
            ['parent_id' => 30, 'child_id' => 239, 'depth' => 2],
            ['parent_id' => 30, 'child_id' => 240, 'depth' => 2],
            ['parent_id' => 30, 'child_id' => 241, 'depth' => 2],
            ['parent_id' => 30, 'child_id' => 242, 'depth' => 2],
            ['parent_id' => 31, 'child_id' => 243, 'depth' => 2],
            ['parent_id' => 31, 'child_id' => 244, 'depth' => 2],
            ['parent_id' => 31, 'child_id' => 245, 'depth' => 2],
            ['parent_id' => 31, 'child_id' => 246, 'depth' => 2],
            ['parent_id' => 31, 'child_id' => 247, 'depth' => 2],
            ['parent_id' => 31, 'child_id' => 248, 'depth' => 2],
            ['parent_id' => 32, 'child_id' => 249, 'depth' => 2],
            ['parent_id' => 32, 'child_id' => 250, 'depth' => 2],
            ['parent_id' => 32, 'child_id' => 251, 'depth' => 2],
            ['parent_id' => 32, 'child_id' => 252, 'depth' => 2],
            ['parent_id' => 33, 'child_id' => 253, 'depth' => 2],
            ['parent_id' => 33, 'child_id' => 254, 'depth' => 2],
            ['parent_id' => 33, 'child_id' => 255, 'depth' => 2],
            ['parent_id' => 34, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 35, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 36, 'child_id' => 256, 'depth' => 2],
            ['parent_id' => 36, 'child_id' => 257, 'depth' => 2],
            ['parent_id' => 36, 'child_id' => 258, 'depth' => 2],
            ['parent_id' => 37, 'child_id' => 259, 'depth' => 2],
            ['parent_id' => 37, 'child_id' => 260, 'depth' => 2],
            ['parent_id' => 37, 'child_id' => 261, 'depth' => 2],
            ['parent_id' => 38, 'child_id' => 262, 'depth' => 2],
            ['parent_id' => 38, 'child_id' => 263, 'depth' => 2],
            ['parent_id' => 38, 'child_id' => 264, 'depth' => 2],
            ['parent_id' => 39, 'child_id' => 265, 'depth' => 2],
            ['parent_id' => 39, 'child_id' => 266, 'depth' => 2],
            ['parent_id' => 39, 'child_id' => 267, 'depth' => 2],
            ['parent_id' => 40, 'child_id' => 268, 'depth' => 2],
            ['parent_id' => 40, 'child_id' => 269, 'depth' => 2],
            ['parent_id' => 40, 'child_id' => 270, 'depth' => 2],
            ['parent_id' => 41, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 42, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 43, 'child_id' => 271, 'depth' => 2],
            ['parent_id' => 43, 'child_id' => 272, 'depth' => 2],
            ['parent_id' => 43, 'child_id' => 273, 'depth' => 2],
            ['parent_id' => 43, 'child_id' => 274, 'depth' => 2],
            ['parent_id' => 43, 'child_id' => 275, 'depth' => 2],
            ['parent_id' => 43, 'child_id' => 276, 'depth' => 2],
            ['parent_id' => 43, 'child_id' => 277, 'depth' => 2],
            ['parent_id' => 44, 'child_id' => 278, 'depth' => 2],
            ['parent_id' => 44, 'child_id' => 272, 'depth' => 2],
            ['parent_id' => 44, 'child_id' => 279, 'depth' => 2],
            ['parent_id' => 44, 'child_id' => 280, 'depth' => 2],
            ['parent_id' => 45, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 46, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 47, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 48, 'child_id' => 281, 'depth' => 2],
            ['parent_id' => 48, 'child_id' => 282, 'depth' => 2],
            ['parent_id' => 48, 'child_id' => 283, 'depth' => 2],
            ['parent_id' => 48, 'child_id' => 284, 'depth' => 2],
            ['parent_id' => 49, 'child_id' => 285, 'depth' => 2],
            ['parent_id' => 49, 'child_id' => 286, 'depth' => 2],
            ['parent_id' => 49, 'child_id' => 287, 'depth' => 2],
            ['parent_id' => 50, 'child_id' => 288, 'depth' => 2],
            ['parent_id' => 50, 'child_id' => 289, 'depth' => 2],
            ['parent_id' => 50, 'child_id' => 290, 'depth' => 2],
            ['parent_id' => 51, 'child_id' => 291, 'depth' => 2],
            ['parent_id' => 51, 'child_id' => 292, 'depth' => 2],
            ['parent_id' => 51, 'child_id' => 293, 'depth' => 2],
            ['parent_id' => 51, 'child_id' => 294, 'depth' => 2],
            ['parent_id' => 51, 'child_id' => 295, 'depth' => 2],
            ['parent_id' => 51, 'child_id' => 296, 'depth' => 2],
            ['parent_id' => 52, 'child_id' => 297, 'depth' => 2],
            ['parent_id' => 52, 'child_id' => 298, 'depth' => 2],
            ['parent_id' => 52, 'child_id' => 299, 'depth' => 2],
            ['parent_id' => 53, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 54, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 55, 'child_id' => 300, 'depth' => 2],
            ['parent_id' => 55, 'child_id' => 301, 'depth' => 2],
            ['parent_id' => 55, 'child_id' => 302, 'depth' => 2],
            ['parent_id' => 55, 'child_id' => 303, 'depth' => 2],
            ['parent_id' => 55, 'child_id' => 304, 'depth' => 2],
            ['parent_id' => 55, 'child_id' => 305, 'depth' => 2],
            ['parent_id' => 55, 'child_id' => 306, 'depth' => 2],
            ['parent_id' => 55, 'child_id' => 307, 'depth' => 2],
            ['parent_id' => 56, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 57, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 58, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 59, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 60, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 61, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 62, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 63, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 64, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 65, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 66, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 67, 'child_id' => 141, 'depth' => 2],
            ['parent_id' => 68, 'child_id' => 308, 'depth' => 2],
            ['parent_id' => 68, 'child_id' => 309, 'depth' => 2],
            ['parent_id' => 68, 'child_id' => 310, 'depth' => 2],
        ]);

        Product::factory(50)->create();
        Shop::factory(50)->create();
        PurchaseDetail::factory(50)->create();
    }
}
